### ISSUE TITLE
Building or installing it , who ?

### ISSUE THREAD

**Issue by ghost** [EvolveLabs/node-mumble-audio#1]
When i do

```
npm install electron-build-tools -g
```

it fails with this output:

```

npm install electron-build-tools -g
npm ERR! Linux 4.2.0-16-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "electron-build-tools" "-g"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on http://registry.npmjs.org/electron-build-tools
npm ERR! 404 
npm ERR! 404 'electron-build-tools' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/cronos/lasertag/tests/npm-debug.log

```

When i do npm install node-mumble-audio it fails, because it would like to download

```

https://s3.amazonaws.com/evolve-bin/node-mumble-audio/node-mumble-audio-0.2.5-linux-x64-release.tgz

```

Please, please help me :fearful: 
Thanks in advance.

**Comment by justinmchase** [comment]
There are builds for mac and windows but the linux build never quite got there.

You can actually get it to work locally by cloning this project and then linking it. Something like:

```
$ git clone git@github.com:evolvelabs/node-mumble-audio.git
$ cd node-mumble-audio 
$ npm link
$ cd ../myapp
$ npm link node-mumble-audio
```

Then it will just build it locally rather than trying to get it out of s3. There are a bunch of dependencies which may also be missing linux binaries, you'll have to link them all and build them all locally.

But this project isn't really maintained anymore so you may even be better off trying your own solution and just use this as a reference. This did work once upon a time!

One trick if you go down this path is to make sure you run this in a different process than your main app.  I was using it in electron and it was too much for a single process to handle, running in a child process worked great though.
